config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users do
    get 'login', :on => :collection
    post 'signin', :on => :collection
    get 'logout', :on => :collection
  end	

  resources :doctors do
    get 'login', :on => :collection
    post 'signin', :on => :collection
    get 'logout', :on => :collection
  end

  resources :doctor_appointments  
  resources :prescriptions
  resources :prescribed_medicines do
    get 'filtered', :on => :collection
  end

  resources :medicines

  get 'home/index'
  root :to => 'home#index'

  get 'about/index'
end

app/models/medicine.rb
class Medicine < ApplicationRecord
	validates_presence_of  :name, :description, :is_acidic
end

app/controllers/medicines_controller.rb
class MedicinesController < ApplicationController
  before_action :set_medicine, only: [:show, :edit, :update, :destroy]

  # GET /medicines
  # GET /medicines.json
  def index
    @medicines = Medicine.all
  end

  # GET /medicines/1
  # GET /medicines/1.json
  def show
  end

  # GET /medicines/new
  def new
    @medicine = Medicine.new
  end

  # GET /medicines/1/edit
  def edit
  end

  # POST /medicines
  # POST /medicines.json
  def create
    @medicine = Medicine.new(medicine_params)

    respond_to do |format|
      if @medicine.save
        format.html { redirect_to @medicine, notice: 'Medicine was successfully created.' }
        format.json { render :show, status: :created, location: @medicine }
      else
        format.html { render :new }
        format.json { render json: @medicine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /medicines/1
  # PATCH/PUT /medicines/1.json
  def update
    respond_to do |format|
      if @medicine.update(medicine_params)
        format.html { redirect_to @medicine, notice: 'Medicine was successfully updated.' }
        format.json { render :show, status: :ok, location: @medicine }
      else
        format.html { render :edit }
        format.json { render json: @medicine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medicines/1
  # DELETE /medicines/1.json
  def destroy
    @medicine.destroy
    respond_to do |format|
      format.html { redirect_to medicines_url, notice: 'Medicine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medicine
      @medicine = Medicine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def medicine_params
      params.require(:medicine).permit(:name, :description, :medicine_type, :is_acidic, :infant_safe)
    end
end

app/helpers/medicines_helper.rb
module MedicinesHelper
end

app/views/medicines/_form.html.erb
<%= form_with(model: medicine, class: 'pure-form pure-form-aligned', local: true) do |form| %>
  <% if medicine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(medicine.errors.count, "error") %> prohibited this medicine from being saved:</h2>

      <ul>
      <% medicine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, class: "control-label col-sm-2" %>
    <div class="col-sm-4">
      <%= form.text_field :name, id: :medicine_name, class: "form-control"%>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :description, class: "control-label col-sm-2" %>
    <div class="col-sm-4">
      <%= form.text_area :description, id: :medicine_description, class: "form-control"%>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :medicine_type, class: "control-label col-sm-2" %>
    <div class="col-sm-4">
      <%= form.check_box :medicine_type, id: :medicine_medicine_type%>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :is_acidic, class: "control-label col-sm-2" %>
    <div class="col-sm-4">
      <%= form.check_box :is_acidic, id: :medicine_is_acidic%>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :infant_safe, class: "control-label col-sm-2" %>
    <div class="col-sm-4">
      <%= form.check_box :infant_safe, id: :medicine_infant_safe%>
    </div>
  </div>

  <div class="form-group">
    <%= form.submit 'submit', class: 'btn btn-primary'%> |
    <%= link_to 'Back', medicines_path, class: 'btn btn-secondary'  %>
  </div>
<% end %>

app/views/medicines/edit.html.erb
<h1>Editing Medicine</h1>

<%= render 'form', medicine: @medicine %>

<%= link_to 'Show', @medicine, class: 'pure-button  pure-button-primary'  %> |
<%= link_to 'Back', medicines_path, class: 'pure-button  button-secondary'  %>

app/views/medicines/index.html.erb
<div style="margin-left:2%;margin-top: 2%;">      

  <h1>Medicines |   <%= link_to 'New Medicine', new_medicine_path, class: 'btn btn-primary'  %></h1>

  <table id="medicines-records" class="table table-striped table-bordered" style="width: 1000px;">
    <thead>
      <tr class="<%= cycle('pure-table-odd', '') -%>">
        <th>ID</th>
        <th>Name</th>
        <th>Description</th>
        <th>Type</th>
        <th>Is acidic</th>
        <th>Infant safe</th>
      </tr>
    </thead>

    <tbody>
      <% @medicines.each do |medicine| %>
        <tr class="<%= cycle('pure-table-odd', '') -%>">
          <td>    <%= link_to medicine_path(medicine.id) do %>
<%= medicine.id %> <%end%></td>
          <td><%= medicine.name %></td>
          <td><%= medicine.description %></td>
          <td><%= medicine.medicine_type %></td>
          <td><%= medicine.is_acidic %></td>
          <td><%= medicine.infant_safe %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<script type="text/javascript">
  $(document).ready(function() {
    $('#medicines-records').DataTable();
  });
</script>

app/views/medicines/new.html.erb
<div style="margin-left: 2%;margin-top: 2%;margin-bottom: 2%;">  	
	<h1>New Medicine</h1>

	<%= render 'form', medicine: @medicine %>
</div>

app/views/medicines/show.html.erb
<div style="margin-left:2%;margin-top: 2%;">  
  
  <p>
    <strong>Name:</strong>
    <%= @medicine.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @medicine.description %>
  </p>

  <p>
    <strong>Type:</strong>
    <%= @medicine.medicine_type %>
  </p>

  <p>
    <strong>Is acidic:</strong>
    <%= @medicine.is_acidic %>
  </p>

  <p>
    <strong>Infant safe:</strong>
    <%= @medicine.infant_safe %>
  </p>

  <%= link_to 'Edit', edit_medicine_path(@medicine), class: 'btn btn-primary'  %> |
  <%= link_to 'Back', medicines_path, class: 'btn btn-secondary'  %> | 
  <%= link_to 'Destroy', medicine_path(@medicine), method: :delete, data: { confirm: 'Are you sure you want to delete this record?' }, class: 'btn btn-warning'  %>
</div>