config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users do
    get 'login', :on => :collection
    post 'signin', :on => :collection
    get 'logout', :on => :collection
  end	

  resources :doctors do
    get 'login', :on => :collection
    post 'signin', :on => :collection
    get 'logout', :on => :collection
  end

  resources :doctor_appointments  
  resources :prescriptions
  resources :prescribed_medicines do
    get 'filtered', :on => :collection
  end

  resources :medicines

  get 'home/index'
  root :to => 'home#index'

  get 'about/index'
end

app/models/prescription.rb
class Prescription < ApplicationRecord
	belongs_to :user
	belongs_to :doctor
	has_many :prescribed_medicines,dependent: :destroy

	validates_presence_of  :notes, :prescribed_on, :valid_till
end

app/controllers/prescriptions_controller.rb
class PrescriptionsController < ApplicationController
  before_action :set_prescription, only: [:show, :edit, :update, :destroy]
  before_action :set_doctors_and_users, only: [:new, :edit]
  before_action :set_doctor_user_from_session, only: [:index, :new]

  # GET /prescriptions
  # GET /prescriptions.json
  def index
    if @doctor && @user
      @prescriptions = Prescription.where(user_id: @user.id, doctor_id: @doctor.id)
    elsif @doctor
      @prescriptions = Prescription.where(doctor_id: @doctor.id)
    elsif @user
      @prescriptions = Prescription.where(user_id: @user.id)
    else
      @prescriptions = Prescription.all
    end
  end

  # GET /prescriptions/1
  # GET /prescriptions/1.json
  def show
  end

  # GET /prescriptions/new
  def new
    @prescription = Prescription.new
  end

  # GET /prescriptions/1/edit
  def edit
  end

  # POST /prescriptions
  # POST /prescriptions.json
  def create
    @prescription = Prescription.new(prescription_params)

    respond_to do |format|
      if @prescription.save
        format.html { redirect_to @prescription, notice: 'Prescription was successfully created.' }
        format.json { render :show, status: :created, location: @prescription }
      else
        format.html { render :new }
        format.json { render json: @prescription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prescriptions/1
  # PATCH/PUT /prescriptions/1.json
  def update
    respond_to do |format|
      if @prescription.update(prescription_params)
        format.html { redirect_to @prescription, notice: 'Prescription was successfully updated.' }
        format.json { render :show, status: :ok, location: @prescription }
      else
        format.html { render :edit }
        format.json { render json: @prescription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prescriptions/1
  # DELETE /prescriptions/1.json
  def destroy
    @prescription.destroy
    respond_to do |format|
      format.html { redirect_to prescriptions_url, notice: 'Prescription was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prescription
      @prescription = Prescription.find(params[:id])
    end

    def set_doctors_and_users
      @doctors = Doctor.all
      @users = User.all
    end

    def set_doctor_user_from_session
      #initialise ids
      doctor_id = nil
      user_id = nil

      # find user
      if session[:user_id]
        user_id = session[:user_id]
      elsif request.query_parameters['userId']
        user_id = request.query_parameters['userId']
      end
      if user_id
        @user = User.find(user_id)
      end

      # find doctor
      if session[:doctor_id]
        doctor_id = session[:doctor_id]
      elsif request.query_parameters['doctorId']
        doctor_id = request.query_parameters['doctorId']
      end
      if doctor_id
        @doctor = Doctor.find(doctor_id)
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prescription_params
      params.require(:prescription).permit(:user_id, :doctor_id, :notes, :prescribed_on, :valid_till)
    end
end

app/helpers/prescriptions_helper.rb
module PrescriptionsHelper
end

app/views/prescriptions/_form.html.erb
<%= form_with(model: prescription, class: 'form-horizontal pure-form pure-form-aligned', local: true) do |form| %>
  <% if prescription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(prescription.errors.count, "error") %> prohibited this prescription from being saved:</h2>

      <ul>
      <% prescription.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <% if @doctor %>
    <div>Doctor: <%= @doctor.first_name %>&nbsp;<%= @doctor.last_name %></div>
    <%= form.hidden_field :doctor_id, :value => @doctor.id%>
  <% else %>
    <div class="form-group">
      <%= form.label :doctor_id , class: "control-label col-sm-2"%>
      <div class="col-sm-4">
      	<%= form.select :doctor_id, options_for_select(@doctors.map{ |d| [d.first_name+' '+d.last_name, d.id, {'username'=>d.username}] }, selected_key = form.object.doctor_id), class: "form-control" %>
    </div>
  <% end %>

  <% if @user %>
    <div >User: <%= @user.first_name %>&nbsp;<%= @user.last_name %></div>
    <%= form.hidden_field :user_id, :value => @user.id%>
  <% else %>
    <div class="form-group">
      <%= form.label :user_id , class: "control-label col-sm-2"%>
      <div class="col-sm-4">
      	<%= form.select :user_id, options_for_select(@users.map{ |u| [u.first_name+' '+u.last_name, u.id, {'username'=>u.username}] }, selected_key = form.object.user_id) , class: "form-control"%>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :notes , class: "control-label col-sm-2"%>
    <div class="col-sm-4">
    	<%= form.text_area :notes, id: :prescription_notes , class: "form-control"%>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :prescribed_on , class: "control-label col-sm-2"%>
    <div class="col-sm-4">
    	<%= form.datetime_select :prescribed_on, id: :prescription_prescribed_on , class: "form-control"%>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :valid_till  , class: "control-label col-sm-2"%>
    <div class="col-sm-4">
    	<%= form.datetime_select :valid_till, id: :prescription_valid_till %>
    </div>
  </div>

  <div class="form-group">
    <%= form.submit 'submit', class: 'btn btn-primary'%> |
    <%= link_to 'Back', prescriptions_path, class: 'btn btn-secondary'  %>
  </div>
<% end %>

app/views/prescriptions/edit.html.erb
<div style="margin-left: 2%;margin-top: 2%;margin-bottom: 2%;">  		
	<h1>Editing Prescription</h1>

	<%= render 'form', prescription: @prescription %>

	<%#= link_to 'Show', @prescription, class: 'pure-button  pure-button-primary'  %> 
</div>

app/views/prescriptions/index.html.erb
<div style="margin-left:2%;margin-top: 2%;">  
    
  <h1>Prescriptions |   <%= link_to 'New Prescription', new_prescription_path, class: 'btn btn-primary'  %></h1>
  <% if @user %>
    <h3>User: <%= @user.first_name %>&nbsp;<%= @user.last_name %></h3>
  <% end %>
  <% if @doctor %>
    <h3>Doctor: <%= @doctor.first_name %>&nbsp;<%= @doctor.last_name %></h3>
  <% end %>

  <table id="prescriptions-records" class="table table-striped table-bordered" style="width: 1000px;">
    <thead>
      <tr class="<%= cycle('pure-table-odd', '') -%>">
        <th>ID</th>
        <th>User</th>
        <th>Doctor</th>
        <th>Notes</th>
        <th>Prescribed on</th>
        <th>Valid till</th>
      </tr>
    </thead>

    <tbody>
      <% @prescriptions.each do |prescription| %>
        <tr class="<%= cycle('pure-table-odd', '') -%>">
          <td>    <%= link_to prescription_path(prescription.id) do %>
<%= prescription.id %> <%end%></td>
          <td><%= prescription.user.first_name%>&nbsp;<%= prescription.user.last_name%></td>
          <td><%= prescription.doctor.first_name%>&nbsp;<%= prescription.doctor.last_name%></td>
          <td><%= prescription.notes %></td>
          <td><%= prescription.prescribed_on %></td>
          <td><%= prescription.valid_till %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<script type="text/javascript">
  $(document).ready(function() {
    $('#prescriptions-records').DataTable();
  });
</script>

app/views/prescriptions/new.html.erb
<div style="margin-left: 2%;margin-top: 2%;margin-bottom: 2%;">  	
	<h1>New Prescription</h1>

	<%= render 'form', prescription: @prescription %>
</div>

app/views/prescriptions/show.html.erb
<div style="margin-left:2%;margin-top: 2%;margin-bottom: 2%;">      
  <p>
    <strong>User:</strong>
    <%= @prescription.user .first_name%>&nbsp;<%=@prescription.user.last_name%>
  </p>

  <p>
    <strong>Doctor:</strong>
    <%= @prescription.doctor.first_name%>&nbsp;<%= @prescription.doctor.last_name%>
  </p>

  <p>
    <strong>Notes:</strong>
    <%= @prescription.notes %>
  </p>

  <p>
    <strong>Prescribed on:</strong>
    <%= @prescription.prescribed_on %>
  </p>

  <p>
    <strong>Valid till:</strong>
    <%= @prescription.valid_till %>
  </p>

  <%= link_to 'Edit', edit_prescription_path(@prescription), class: 'btn btn-primary'  %> |
  <%= link_to 'Back', prescriptions_path, class: 'btn btn-secondary'  %> | 
  <%= link_to 'Destroy', prescription_path(@prescription), method: :delete, data: { confirm: 'Are you sure you want to delete this record?' }, class: 'btn btn-warning'  %>

  <br />
  <br />
  <hr/>

  <h3>Prescribed Medicines</h3>

  <table id="prescribed_medicines-records" class="table table-striped table-bordered" style="width: 1000px;">
    <thead>
      <tr class="<%= cycle('pure-table-odd', '') -%>">
        <th>ID</th>
        <th>Medicine</th>
        <th>Prescription</th>
        <th>Notes</th>
        <th>Before breakfast</th>
        <th>After breakfast</th>
        <th>Before lunch</th>
        <th>After lunch</th>
        <th>Before dinner</th>
        <th>After dinner</th>
        <th>Available Count</th>
      </tr>
    </thead>

    <tbody>
      <% @prescription.prescribed_medicines.each do |prescribed_medicine| %>
        <tr class="<%= cycle('pure-table-odd', '') -%>">
          <td>    <%= link_to prescribed_medicine_path(prescribed_medicine.id) do %>
  <%= prescribed_medicine.id %> <%end%></td>
          <td><%= prescribed_medicine.medicine.name %></td>
          <td><%= prescribed_medicine.prescription.notes %></td>
          <td><%= prescribed_medicine.notes %></td>
          <td><%= prescribed_medicine.before_breakfast %></td>
          <td><%= prescribed_medicine.after_breakfast %></td>
          <td><%= prescribed_medicine.before_lunch %></td>
          <td><%= prescribed_medicine.after_lunch %></td>
          <td><%= prescribed_medicine.before_dinner %></td>
          <td><%= prescribed_medicine.after_dinner %></td>
          <td><%= prescribed_medicine.available_count %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= link_to 'Add Prescribed Medicine', new_prescribed_medicine_path(:prescriptionId => @prescription.id), class: 'btn btn-secondary' %>
</div>

<script type="text/javascript">
  $(document).ready(function() {
    $('#prescribed_medicines-records').DataTable();
  });
</script>