config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users do
    get 'login', :on => :collection
    post 'signin', :on => :collection
    get 'logout', :on => :collection
  end	

  resources :doctors do
    get 'login', :on => :collection
    post 'signin', :on => :collection
    get 'logout', :on => :collection
  end

  resources :doctor_appointments  
  resources :prescriptions
  resources :prescribed_medicines do
    get 'filtered', :on => :collection
  end

  resources :medicines

  get 'home/index'
  root :to => 'home#index'

  get 'about/index'
end

app/models/prescribed_medicine.rb
class PrescribedMedicine < ApplicationRecord
  belongs_to :medicine
  belongs_to :prescription
end

app/controllers/prescribed_medicines_controller.rb
require 'time'

class PrescribedMedicinesController < ApplicationController
  before_action :set_prescribed_medicine, only: [:show, :edit, :update, :destroy]
  before_action :set_medicines_and_prescriptions, only: [:new, :edit]
  before_action :set_prescription_medicines_from_param, only: [:index, :new, :filtered]

  # GET /prescribed_medicines
  # GET /prescribed_medicines.json
  def index
    load_data_based_on_session
  end


  # GET /prescribed_medicines/filtered
  # GET /prescribed_medicines/filtered.json
  def filtered
    load_data_based_on_session
    part_of_day = get_part_of_day
    if part_of_day
      case part_of_day
      when "morning"
        start = DateTime.now.change({ hour: 6, min: 0, sec: 0 })
        finish = DateTime.now.change({ hour: 11, min: 0, sec: 0 })
      when "noon"
        start = DateTime.now.change({ hour: 12, min: 0, sec: 0 })
        finish = DateTime.now.change({ hour: 17, min: 0, sec: 0 })
      when "night"
        start = DateTime.now.change({ hour: 18, min: 0, sec: 0 })
        finish = DateTime.now.change({ hour: 22, min: 0, sec: 0 })
      end
      _medicine_intake_logs = MedicineIntakeLog.where(:logged_on => start..finish)
      _prescribed_medicines_ids = _medicine_intake_logs.map{|pm| pm.id}
      if !@prescribed_medicines.empty?
          @prescribed_medicines = @prescribed_medicines.where.not(id: _prescribed_medicines_ids)
      end
    end
  end


  # GET /prescribed_medicines/1
  # GET /prescribed_medicines/1.json
  def show
  end

  # GET /prescribed_medicines/new
  def new
    @prescribed_medicine = PrescribedMedicine.new
  end

  # GET /prescribed_medicines/1/edit
  def edit
  end

  # POST /prescribed_medicines
  # POST /prescribed_medicines.json
  def create
    @prescribed_medicine = PrescribedMedicine.new(prescribed_medicine_params)

    respond_to do |format|
      if @prescribed_medicine.save
        format.html { redirect_to @prescribed_medicine, notice: 'Prescribed medicine was successfully created.' }
        format.json { render :show, status: :created, location: @prescribed_medicine }
      else
        format.html { render :new }
        format.json { render json: @prescribed_medicine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prescribed_medicines/1
  # PATCH/PUT /prescribed_medicines/1.json
  def update
    respond_to do |format|
      if @prescribed_medicine.update(prescribed_medicine_params)
        format.html { redirect_to @prescribed_medicine, notice: 'Prescribed medicine was successfully updated.' }
        format.json { render :show, status: :ok, location: @prescribed_medicine }
      else
        format.html { render :edit }
        format.json { render json: @prescribed_medicine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prescribed_medicines/1
  # DELETE /prescribed_medicines/1.json
  def destroy
    @prescribed_medicine.destroy
    respond_to do |format|
      format.html { redirect_to prescribed_medicines_url, notice: 'Prescribed medicine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prescribed_medicine
      @prescribed_medicine = PrescribedMedicine.find(params[:id])
    end

    def set_medicines_and_prescriptions
      @medicines = Medicine.all
      @prescriptions = Prescription.all
    end

    def set_prescription_medicines_from_param
      _medicine_id = request.query_parameters['medicineId']
      _prescription_id = request.query_parameters['prescriptionId']
      time_param = request.query_parameters['time']
      _user_id = session[:user_id] ? session[:user_id] : request.query_parameters['userId']

      if _medicine_id
        @medicine = Medicine.find(medicine_id)
      end
      if _prescription_id
        @prescription = Prescription.find(_prescription_id)
      end

      if _user_id
        @user = User.find(_user_id)
      end

      if time_param == 'now'
        @part_of_day = get_part_of_day
      end
    end

    def get_part_of_day
      _hour = Time.now.hour
      part_of_day = 'morning'
      if _hour > 5 && _hour < 12
        part_of_day = 'morning'
      elsif _hour >=12 && _hour < 18
        part_of_day = 'noon'
      elsif _hour >=18 && _hour < 22
        part_of_day = 'night'
      end
      puts part_of_day
      return part_of_day
    end

    def load_data_based_on_session
      if @user
          _prescription_ids = @user.prescriptions.map{|pr| pr.id}
          @prescribed_medicines = PrescribedMedicine.where(prescription_id: _prescription_ids)
          if @part_of_day
            case @part_of_day
            when "morning"
              condition = 'before_breakfast=? OR after_breakfast=?'
            when "noon"
              condition = 'before_lunch=? OR after_lunch=?'
            when "night"
              condition = 'before_lunch=? OR after_lunch=?'
            end
            @prescribed_medicines = @prescribed_medicines.where(condition, 't', 't')
         end
      else
        if @prescription && @medicine
          @prescribed_medicines = PrescribedMedicine.where(prescription_id: @prescription.id, medicine_id: @medicine.id)
        elsif @prescription
          @prescribed_medicines = PrescribedMedicine.where(prescription_id: @prescription.id)
        elsif @medicine
          @prescribed_medicines = PrescribedMedicine.where(medicine_id: @medicine.id)
        else
          if @part_of_day
            case @part_of_day
            when "morning"
              condition = 'before_breakfast=? OR after_breakfast=?'
            when "noon"
              condition = 'before_lunch=? OR after_lunch=?'
            when "night"
                condition = 'before_lunch=? OR after_lunch=?'
            end
            @prescribed_medicines = @prescribed_medicines.where(condition, 't', 't')
          else
            @prescribed_medicines = PrescribedMedicine.all
          end
        end
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def prescribed_medicine_params
      params.require(:prescribed_medicine).permit(:medicine_id, :prescription_id, :notes, :before_breakfast, :after_breakfast, :before_lunch, :after_lunch, :before_dinner, :after_dinner, :available_count)
    end
end

app/helpers/prescribed_medicines_helper.rb
module PrescribedMedicinesHelper
end

app/views/prescribed_medicines/_form.html.erb
<%= form_with(model: prescribed_medicine, class: 'pure-form pure-form-aligned', local: true) do |form| %>
  <% if prescribed_medicine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(prescribed_medicine.errors.count, "error") %> prohibited this prescribed_medicine from being saved:</h2>

      <ul>
      <% prescribed_medicine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% if @medicine %>
    <div>Medicine: <%= @medicine.name%></div>
    <%= form.hidden_field :medicine_id, :value => @medicine.id%>
  <% else %>
    <div class="form-group">
      <%= form.label :medicine_id, class: "control-label col-sm-2" %>
      <div class="col-sm-4">
        <%= form.select :medicine_id, options_for_select(@medicines.map{ |m| [m.name, m.id, {'name'=>m.name}] }, selected_key = form.object.medicine_id) ,class: "form-control"%>
      </div>
    </div>
  <% end %>

  <% if @prescription %>
    <div>Prescription: <%= @prescription.notes %></div>
    <%= form.hidden_field :prescription_id, :value => @prescription.id%>
  <% else %>
    <div class="form-group">
      <%= form.label :prescription_id, class: "control-label col-sm-2" %>
      <div class="col-sm-4">
        <%= form.select :prescription_id, options_for_select(@prescriptions.map{ |pr| [pr.notes, pr.id, {'notes'=>pr.notes}] }, selected_key = form.object.prescription_id),class: "form-control" %>
      </div>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :notes,  class: "control-label col-sm-2" %>
    <div class="col-sm-4">
      <%= form.text_area :notes, id: :prescribed_medicine_notes ,class: "form-control"%>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :before_breakfast ,  class: "control-label col-sm-2"%>
    <div class="col-sm-4">
      <%= form.check_box :before_breakfast, id: :prescribed_medicine_before_breakfast %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :after_breakfast ,  class: "control-label col-sm-2"%>
    <div class="col-sm-4">
      <%= form.check_box :after_breakfast, id: :prescribed_medicine_after_breakfast%>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :before_lunch ,  class: "control-label col-sm-2"%>
    <div class="col-sm-4">
      <%= form.check_box :before_lunch, id: :prescribed_medicine_before_lunch%>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :after_lunch ,  class: "control-label col-sm-2"%>
    <div class="col-sm-4">
      <%= form.check_box :after_lunch, id: :prescribed_medicine_after_lunch %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :before_dinner ,  class: "control-label col-sm-2"%>
    <div class="col-sm-4">
      <%= form.check_box :before_dinner, id: :prescribed_medicine_before_dinner %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :after_dinner ,  class: "control-label col-sm-2"%>
    <div class="col-sm-4">
      <%= form.check_box :after_dinner, id: :prescribed_medicine_after_dinner %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :available_count ,  class: "control-label col-sm-2"%>
    <div class="col-sm-4">
      <%= form.text_field :available_count, id: :prescribed_medicine_available_count,class: "form-control"%>
    </div>
  </div>

  <div class="actions">
    <%= form.submit 'submit', :class => 'btn btn-primary'%> |
    <%= link_to 'Back', prescribed_medicines_path, class: 'btn btn-secondary'  %>  
  </div>
<% end %>

app/views/prescribed_medicines/edit.html.erb
<div style="margin-left: 2%;margin-top: 2%;margin-bottom: 2%;">  		
	
	<h1>Editing Prescribed Medicine</h1>

	<%= render 'form', prescribed_medicine: @prescribed_medicine %>

	<%= link_to 'Show', @prescribed_medicine, class: 'btn btn-primary'  %> |
</div>

app/views/prescribed_medicines/filtered.html.erb
<h1>Prescribed Medicines</h1>

<% if @medicine %>
  <h3>Medicine: <%= @medicine.name%></h3>
<% end %>
<% if @prescription %>
  <h3>Prescription: <%= @prescription.notes %></h3>
<% end %>

<table class="pure-table pure-table-bordered">
  <thead>
    <tr class="<%= cycle('pure-table-odd', '') -%>">
      <th>Medicine</th>
      <th>Prescription</th>
      <th>Notes</th>
      <th>Before breakfast</th>
      <th>After breakfast</th>
      <th>Before lunch</th>
      <th>After lunch</th>
      <th>Before dinner</th>
      <th>After dinner</th>
      <th>Available Count</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @prescribed_medicines.each do |prescribed_medicine| %>
      <tr class="<%= cycle('pure-table-odd', '') -%>">
        <td><%= prescribed_medicine.medicine.name %></td>
        <td><%= prescribed_medicine.prescription.notes %></td>
        <td><%= prescribed_medicine.notes %></td>
        <td><%= prescribed_medicine.before_breakfast %></td>
        <td><%= prescribed_medicine.after_breakfast %></td>
        <td><%= prescribed_medicine.before_lunch %></td>
        <td><%= prescribed_medicine.after_lunch %></td>
        <td><%= prescribed_medicine.before_dinner %></td>
        <td><%= prescribed_medicine.after_dinner %></td>
        <td><%= prescribed_medicine.available_count %></td>
        <td><%= link_to 'Show', prescribed_medicine, class: 'pure-button  pure-button-primary'  %></td>
        <td><%= link_to 'Edit', edit_prescribed_medicine_path(prescribed_medicine), class: 'pure-button  button-secondary'  %></td>
        <td><%= link_to 'Destroy', prescribed_medicine, method: :delete, data: { confirm: 'Are you sure?' }, class: 'pure-button  button-warning'  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Prescribed Medicine', new_prescribed_medicine_path, class: 'pure-button  button-secondary' %>

app/views/prescribed_medicines/index.html.erb
<div style="margin-left:2%;margin-top: 2%;margin-bottom: 2%;">  
  
  <h1>Prescribed Medicines |   <%= link_to 'New Prescribed Medicine', new_prescribed_medicine_path, class: 'btn btn-primary' %></h1>

  <% if @medicine %>
    <h3>Medicine: <%= @medicine.name%></h3>
  <% end %>
  <% if @prescription %>
    <h3>Prescription: <%= @prescription.notes %></h3>
  <% end %>

  <table id="prescribed_medicines-records" class="table table-striped table-bordered" style="width: 1000px;">
    <thead>
      <tr class="<%= cycle('pure-table-odd', '') -%>">
        <th>ID</th>
        <th>Medicine</th>
        <th>Prescription</th>
        <th>Notes</th>
        <th>Before breakfast</th>
        <th>After breakfast</th>
        <th>Before lunch</th>
        <th>After lunch</th>
        <th>Before dinner</th>
        <th>After dinner</th>
        <th>Available Count</th>
      </tr>
    </thead>

    <tbody>
      <% @prescribed_medicines.each do |prescribed_medicine| %>
        <tr class="<%= cycle('pure-table-odd', '') -%>">
          <td>    <%= link_to prescribed_medicine_path(prescribed_medicine.id) do %>
<%= prescribed_medicine.id %> <%end%></td>
          <td><%= prescribed_medicine.medicine.name %></td>
          <td><%= prescribed_medicine.prescription.notes %></td>
          <td><%= prescribed_medicine.notes %></td>
          <td><%= prescribed_medicine.before_breakfast %></td>
          <td><%= prescribed_medicine.after_breakfast %></td>
          <td><%= prescribed_medicine.before_lunch %></td>
          <td><%= prescribed_medicine.after_lunch %></td>
          <td><%= prescribed_medicine.before_dinner %></td>
          <td><%= prescribed_medicine.after_dinner %></td>
          <td><%= prescribed_medicine.available_count %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <h3>Visualisation</h3>
  <%= pie_chart @prescribed_medicines.group(:medicine).sum(:available_count).map{|m, count| [m.name, count]} %>

</div>

<script type="text/javascript">
  $(document).ready(function() {
    $('#prescribed_medicines-records').DataTable();
  });
</script>

app/views/prescribed_medicines/new.html.erb
<div style="margin-left: 2%;margin-top: 2%;margin-bottom: 2%;">  	
  
	<h1>New Prescribed Medicine</h1>

	<%= render 'form', prescribed_medicine: @prescribed_medicine %>
</div>

app/views/prescribed_medicines/show.html.erb
<div style="margin-left:2%;margin-top: 2%;">  
  
  <p>
    <strong>Medicine:</strong>
    <%= @prescribed_medicine.medicine.name %>
  </p>

  <p>
    <strong>Prescription:</strong>
    <%= @prescribed_medicine.prescription.notes %>
  </p>

  <p>
    <strong>Notes:</strong>
    <%= @prescribed_medicine.notes %>
  </p>

  <p>
    <strong>Before breakfast:</strong>
    <%= @prescribed_medicine.before_breakfast %>
  </p>

  <p>
    <strong>After breakfast:</strong>
    <%= @prescribed_medicine.after_breakfast %>
  </p>

  <p>
    <strong>Before lunch:</strong>
    <%= @prescribed_medicine.before_lunch %>
  </p>

  <p>
    <strong>After lunch:</strong>
    <%= @prescribed_medicine.after_lunch %>
  </p>

  <p>
    <strong>Before dinner:</strong>
    <%= @prescribed_medicine.before_dinner %>
  </p>

  <p>
    <strong>After dinner:</strong>
    <%= @prescribed_medicine.after_dinner %>
  </p>

  <p>
    <strong>Availble count:</strong>
    <%= @prescribed_medicine.available_count %>
  </p>

  <%= link_to 'Edit', edit_prescribed_medicine_path(@prescribed_medicine), class: 'btn btn-primary'  %> |
  <%= link_to 'Back', prescribed_medicines_path, class: 'btn btn-secondary'  %> |
  <%= link_to 'Destroy', prescribed_medicine_path(@prescribed_medicine), method: :delete, data: { confirm: 'Are you sure you want to delete this record?' }, class: 'btn btn-warning'  %>
</div>